[INFO  2019-10-21 17:18:05 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[INFO  2019-10-21 17:18:05 @__init__.py:80] Saving logging to file: neuralgym_logs/20191021171805459903.
[INFO  2019-10-21 17:18:06 @_internal.py:122]  * Running on http://172.19.140.150:5003/ (Press CTRL+C to quit)
[ERROR 2019-10-21 17:18:08 @app.py:1891] Exception on /inpainting/api/v1.0/order [POST]
Traceback (most recent call last):
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/data/shared/conda_envs/tf-gpu/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api.py", line 69, in postJsonHandler_multiprocessing
    if Image_inpainting.json_mask_checker(json_content['image_mask'])!=1:
  File "/home/nelson/inpainting_api/model.py", line 83, in json_mask_checker
    elif urlopen(json_image).info()['Content-type'].endswith(("jpg","jpeg")):
NameError: name 'json_image' is not defined
[INFO  2019-10-21 17:18:08 @_internal.py:122] 172.19.140.253 - - [21/Oct/2019 17:18:08] "[1m[35mPOST /inpainting/api/v1.0/order HTTP/1.1[0m" 500 -
